Algoritmo "11.Vetores"
Var
   Nomes: Vetor[0..4] de Caractere
   //isso é um vetor de 5 elementos, pois conta desde o zero.
Inicio
   Nomes [0] <- "João"
   Nomes [1] <- "Maria"
   Nomes [2] <- "José"
   Nomes [3] <- "Rafaela"
   Nomes [4] <- "Jorge"
   
   Escreval(Nomes[0])
   Escreval(Nomes[1])
   Escreval(Nomes[2])
   Escreval(Nomes[3])
   Escreval(Nomes[4])
   //estrutura de repetição faz não precisar escrever todas essas linhas 12 até 16.
Fimalgoritmo